name: ping receiver
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: receiver
        run: echo "${{ github.event.client_payload.ref }}"
