#* local: act.exe -j manual-ping -s GITHUB_TOKEN="$(gh auth token)"
name: curl ping
on:
  #? https://crontab.guru/#0_12_*_*_*
  schedule:
    - cron: '0 12 * * *'
  repository_dispatch:

jobs:
  manual-ping:
    runs-on: ubuntu-latest
    steps:
      #? @see https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
      - name: PING - Dispatch initiating repository event
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ph4un00b/github-actions/dispatches \
          -d '{"event_type":"my-payload","client_payload":{"unit":false,"integration":true}}'
