name: ping the repo
on: workflow_dispatch

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: my-event
