#* local: act.exe -j ping-action -s GITHUB_TOKEN="$(gh auth token)"
name: ping action
on:
  repository_dispatch:

jobs:
  ping-action:
    runs-on: ubuntu-latest
    steps:
      #? @see https://github.com/peter-evans/repository-dispatch#example
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: my-action
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
