#* test: act.exe -j pong-action -s GITHUB_TOKEN="$(gh auth token)" -e .\payload.json
name: modified book files
on:
  repository_dispatch:
    types: [modified-pages]
jobs:
  pong-action:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'payload: ${{ toJSON(github.event.client_payload) }}'"
